Repository HyoZaSon/BackEnd, pull requests merged in 2023-08, with the labels that each got.

#8 [#7/Feat] 도움 요청 글 조회 및 리워드 획득 기능 구현
  src/main/java/com/help/hyozason_backend/controller/helpboard/HelpBoardController.java
  src/main/java/com/help/hyozason_backend/controller/helpreward/HelpRewardController.java
  src/main/java/com/help/hyozason_backend/dto/helpboard/HelpBoardDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpreward/HelpRewardDTO.java
  src/main/java/com/help/hyozason_backend/entity/helpboard/HelpBoardEntity.java
  src/main/java/com/help/hyozason_backend/entity/helpreward/HelpRewardEntity.java
  src/main/java/com/help/hyozason_backend/repository/helpboard/HelpBoardRepository.java
  src/main/java/com/help/hyozason_backend/repository/helpreward/HelpRewardRepository.java
  src/main/java/com/help/hyozason_backend/service/helpboard/HelpBoardService.java
  src/main/java/com/help/hyozason_backend/service/helpreward/HelpRewardService.java
Labels: feat, 정유진

#11 [Feat/#4] 도움 요청과 도메인
  pom.xml
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/dto/helpboard/HelpBoardDTO.java
  src/main/java/com/help/hyozason_backend/dto/helplocation/HelpLocationDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpregion/HelpRegionDTO.java
  src/main/java/com/help/hyozason_backend/dto/helprequest/HelpRequestDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpreward/HelpRewardDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpuser/HelpUserDTO.java
  src/main/java/com/help/hyozason_backend/entity/helpboard/HelpBoardEntity.java
  src/main/java/com/help/hyozason_backend/entity/helplocation/HelpLocationEntity.java
  src/main/java/com/help/hyozason_backend/entity/helpreward/HelpRewardEntity.java
  src/main/java/com/help/hyozason_backend/entity/helpuser/HelpUserEntity.java
  src/main/java/com/help/hyozason_backend/handler/HelpRequestHandler.java
  src/main/java/com/help/hyozason_backend/handler/StompHandler.java
  src/main/java/com/help/hyozason_backend/handler/WebSocketConfiguration.java
  src/main/java/com/help/hyozason_backend/jwt/JwtTokenProvider.java
  src/main/java/com/help/hyozason_backend/repository/helpuser/HelpUserRepository.java
  src/main/java/com/help/hyozason_backend/service/helprequest/HelpRequestService.java
Labels: feat, docs, 이해송

#12 [Feat/#4]도움 요청 + 글 작성 + 문자 api 구현 완료 /테스트 안해봄
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/dto/helpboard/HelpBoardDTO.java
  src/main/java/com/help/hyozason_backend/dto/helplocation/HelpLocationDTO.java
  src/main/java/com/help/hyozason_backend/dto/helprequest/HelpRequestDTO.java
  src/main/java/com/help/hyozason_backend/entity/helpboard/HelpBoardEntity.java
  src/main/java/com/help/hyozason_backend/entity/helplocation/HelpLocationEntity.java
  src/main/java/com/help/hyozason_backend/entity/helpuser/HelpUserEntity.java
  src/main/java/com/help/hyozason_backend/etc/ResponseService.java
  src/main/java/com/help/hyozason_backend/handler/HelpRequestHandler.java
  src/main/java/com/help/hyozason_backend/handler/StompHandler.java
  src/main/java/com/help/hyozason_backend/jwt/JwtTokenProvider.java
  src/main/java/com/help/hyozason_backend/mapper/helplocation/HelpLocationMapper.java
  src/main/java/com/help/hyozason_backend/repository/helplocation/HelpLocationRepository.java
  src/main/java/com/help/hyozason_backend/repository/helpreward/HelpRewardRepository.java
  src/main/java/com/help/hyozason_backend/repository/helpuser/HelpUserRepository.java
  src/main/java/com/help/hyozason_backend/service/helprequest/HelpRequestService.java
  src/main/java/com/help/hyozason_backend/service/helpreward/HelpRewardService.java
Labels: feat, 이해송

#15 [Feat]소셜 로그인,회원가입 구현
  pom.xml
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/controller/helpuser/HelpUserController.java
  src/main/java/com/help/hyozason_backend/dto/helpuser/HelpUserDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpuser/MemberRequestDto.java
  src/main/java/com/help/hyozason_backend/dto/helpuser/MemberResponseDto.java
  src/main/java/com/help/hyozason_backend/entity/helpuser/HelpUserEntity.java
  src/main/java/com/help/hyozason_backend/exception/AuthErrorCode.java
  src/main/java/com/help/hyozason_backend/exception/BaseException.java
  src/main/java/com/help/hyozason_backend/exception/ControllerAdvice.java
  src/main/java/com/help/hyozason_backend/exception/ErrorCode.java
  src/main/java/com/help/hyozason_backend/exception/ExceptionResponse.java
  src/main/java/com/help/hyozason_backend/exception/GlobalErrorCode.java
  src/main/java/com/help/hyozason_backend/exception/MemberErrorCode.java
  src/main/java/com/help/hyozason_backend/exception/ReportError.java
  src/main/java/com/help/hyozason_backend/handler/StompHandler.java
  src/main/java/com/help/hyozason_backend/jwt/JwtTokenProvider.java
  src/main/java/com/help/hyozason_backend/repository/helpuser/HelpUserRepository.java
  src/main/java/com/help/hyozason_backend/security/SecurityConfig.java
  src/main/java/com/help/hyozason_backend/security/auth/CurrentMember.java
  src/main/java/com/help/hyozason_backend/security/auth/CustomAccessDeniedHandler.java
  src/main/java/com/help/hyozason_backend/security/auth/PrincipalDetails.java
  src/main/java/com/help/hyozason_backend/security/auth/PrincipalDetailsService.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtExceptionFilter.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtTokenProvider.java
  src/main/java/com/help/hyozason_backend/service/helpoauth/HelpOauthService.java
  src/main/java/com/help/hyozason_backend/service/helpuser/HelpUserService.java
  src/main/resources/application.properties
Labels: feat, 박지원

#19 [FIX]에러 코드추가 및 parser 수정
  src/main/java/com/help/hyozason_backend/exception/AuthErrorCode.java
  src/main/java/com/help/hyozason_backend/exception/ReportError.java
  src/main/java/com/help/hyozason_backend/service/helpoauth/HelpOauthService.java
Labels: fix, 박지원

#21 [FEAT/#20] Create maven_build.yaml
  .github/workflows/maven_build.yaml
Labels: 이해송

#23 [Feat] 회원가입 주소 추가
  src/main/java/com/help/hyozason_backend/controller/helpuser/HelpUserController.java
  src/main/java/com/help/hyozason_backend/dto/helpregion/HelpRegionDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpuser/MemberRequestDto.java
  src/main/java/com/help/hyozason_backend/entity/helpregion/HelpRegionEntity.java
  src/main/java/com/help/hyozason_backend/exception/ControllerAdvice.java
  src/main/java/com/help/hyozason_backend/exception/MemberErrorCode.java
  src/main/java/com/help/hyozason_backend/repository/helpregion/HelpRegionRepository.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/help/hyozason_backend/service/helpoauth/HelpOauthService.java
  src/main/java/com/help/hyozason_backend/service/helpuser/HelpUserService.java
Labels: feat, 박지원

#25 [Feat]토큰 갱신 구현
  src/main/java/com/help/hyozason_backend/controller/helpuser/HelpUserController.java
  src/main/java/com/help/hyozason_backend/etc/Role.java
  src/main/java/com/help/hyozason_backend/security/SecurityConfig.java
  src/main/java/com/help/hyozason_backend/security/auth/PrincipalDetails.java
  src/main/java/com/help/hyozason_backend/security/auth/PrincipalDetailsService.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtTokenProvider.java
  src/main/java/com/help/hyozason_backend/service/helpuser/HelpUserService.java
  src/main/resources/application.properties
Labels: feat, 박지원

#26 [fix/#16] : 오류 해결중 프론트 전달 위해 중간저장
  src/main/java/com/help/hyozason_backend/HyozasonBackendApplication.java
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/dto/helpboard/HelpBoardDTO.java
  src/main/java/com/help/hyozason_backend/dto/helprequest/HelpRequestDTO.java
  src/main/java/com/help/hyozason_backend/service/helprequest/HelpRequestService.java
  src/main/java/com/help/hyozason_backend/socket/HelpRequestHandler.java
  src/main/java/com/help/hyozason_backend/socket/MyHandShakeInterceptor.java
  src/main/java/com/help/hyozason_backend/socket/StompHandler.java
  src/main/java/com/help/hyozason_backend/socket/WebSocketConfiguration.java
  src/main/java/com/help/hyozason_backend/socket/WebSocketEventListener.java
  src/main/resources/application.properties
  src/test/java/com/help/hyozason_backend/helprequesttest/HelpRequestTest.java
Labels: fix, 이해송

#28 [Fix/#16] 코드 보완 ( 아직 연결 이슈 있음)
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/dto/helplocation/HelpLocationDTO.java
  src/main/java/com/help/hyozason_backend/dto/helprequest/HelpRequestDTO.java
  src/main/java/com/help/hyozason_backend/entity/helplocation/HelpLocationEntity.java
  src/main/java/com/help/hyozason_backend/service/helprequest/HelpRequestService.java
  src/test/java/com/help/hyozason_backend/helprequesttest/HelpRequestTest.java
Labels: fix, 이해송

#34 [Fix] 권한 오류 해결 , 로그아웃 구현, 로그인 수정
  pom.xml
  src/main/java/com/help/hyozason_backend/controller/helpboard/HelpBoardController.java
  src/main/java/com/help/hyozason_backend/controller/helpuser/HelpUserController.java
  src/main/java/com/help/hyozason_backend/dto/helpregion/HelpRegionDTO.java
  src/main/java/com/help/hyozason_backend/dto/helpuser/MemberResponseDto.java
  src/main/java/com/help/hyozason_backend/entity/helpuser/HelpUserEntity.java
  src/main/java/com/help/hyozason_backend/etc/Role.java
  src/main/java/com/help/hyozason_backend/exception/CustomErrorController.java
  src/main/java/com/help/hyozason_backend/exception/MemberErrorCode.java
  src/main/java/com/help/hyozason_backend/repository/helpregion/HelpRegionRepository.java
  src/main/java/com/help/hyozason_backend/repository/helpuser/HelpUserRepository.java
  src/main/java/com/help/hyozason_backend/security/SecurityConfig.java
  src/main/java/com/help/hyozason_backend/security/auth/CustomAccessDeniedHandler.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/help/hyozason_backend/security/jwt/JwtTokenProvider.java
  src/main/java/com/help/hyozason_backend/security/redis/RedisConfig.java
  src/main/java/com/help/hyozason_backend/security/redis/RedisUtil.java
  src/main/java/com/help/hyozason_backend/service/helpuser/HelpUserService.java
  src/main/resources/application.properties
Labels: fix, feat, 박지원

#37 [#35/Fix] 글 조회 기능 수정
  pom.xml
  src/main/java/com/help/hyozason_backend/controller/jwt/JwtController.java
  src/main/java/com/help/hyozason_backend/repository/helpregion/HelpRegionRepository.java
  src/main/java/com/help/hyozason_backend/service/helpboard/HelpBoardService.java
  src/main/java/com/help/hyozason_backend/service/helprequest/HelpRequestService.java
  src/main/resources/application.properties
Labels: fix, 정유진

#41 [#40/fix] 도움 요청 및 수락 기능 수정
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/service/helprequest/HelpRequestService.java
Labels: fix, 정유진

#42 [Fix/#16] 도움 요청 / 수락 작성 완료
  pom.xml
  src/main/java/com/help/hyozason_backend/controller/helprequest/HelpRequestController.java
  src/main/java/com/help/hyozason_backend/controller/helprequestsse/CorsConfig.java
  src/main/java/com/help/hyozason_backend/controller/helprequestsse/HelpRequestSSEController.java
  src/main/java/com/help/hyozason_backend/controller/helprequestsse/SseEmitters.java
  src/main/java/com/help/hyozason_backend/controller/helprequestsse/WebConfig.java
  src/main/java/com/help/hyozason_backend/entity/helpboard/HelpBoardEntity.java
  src/main/java/com/help/hyozason_backend/entity/helplocation/HelpLocationEntity.java
  src/main/java/com/help/hyozason_backend/service/helprequestsse/HelpRequestSSEService.java
  src/main/java/com/help/hyozason_backend/socket/HelpRequestHandler.java
  src/main/java/com/help/hyozason_backend/socket/MyHandShakeInterceptor.java
  src/main/java/com/help/hyozason_backend/socket/StompHandler.java
  src/main/java/com/help/hyozason_backend/socket/WebSocketSecurityConfig.java
  src/main/resources/application.properties
Labels: fix, feat, 이해송

#44 [Fix] 로그인 로그아웃 수정
  src/main/java/com/help/hyozason_backend/controller/helpuser/HelpUserController.java
  src/main/java/com/help/hyozason_backend/exception/MemberErrorCode.java
  src/main/java/com/help/hyozason_backend/service/helpuser/HelpUserService.java
Labels: fix

#50 [fix] 키 추가
  src/main/resources/application.properties
Labels: fix

#52 [Fix] 주소수정
  src/main/resources/application.properties
Labels: fix
